-- Create documents table
create table documents (
  id bigint generated by default as identity primary key,
  filename text not null,
  upload_date timestamp with time zone default timezone('utc'::text, now()) not null,
  total_chunks integer not null
);

-- Create chunks table
create table chunk (
  id bigint generated by default as identity primary key,
  document_id bigint references documents(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  embedding_id text not null -- Reference to ChromaDB ID
);
